### ISSUE TITLE
Which machine learning algorithms should we use?

### ISSUE THREAD

**Issue by vmesel** [datasciencebr/rosie#1]
We already know that machine learning algorithms can do magic for us, but we need to select some of them to do the work pretty well. What are the machine learning algorithms that must have in this robot?

**Comment by Irio** [comment]
We're not sure about the algorithms to use here yet, @vmesel. They will come from analyses made in the https://github.com/datasciencebr/serenata-de-amor repo. Feel free to try something you believe will work in a Jupyter Notebook and open a pull request explaining your line of thought.
