### ISSUE TITLE
Use VersionEye to keep tabs of libs

### ISSUE THREAD

**Issue by caduvieira** [datasciencebr/rosie#100]
https://www.versioneye.com to check libs versions and vulnerabilities

**Comment by cuducos** [comment]
Couldn't open the URL:

<img width="732" alt="screen shot 2017-11-07 at 12 39 22" src="https://user-images.githubusercontent.com/4732915/32499094-b8bcc780-c3b8-11e7-93f4-a765e5389a93.png">

Is it somthing like [pyup.io](https://pyup.io) as we use in [Jabras](https://github.com/datasciencebr/jarbas)?

**Comment by caduvieira** [comment]
Yes! If pyup is already being used I guess we should use it here to.
