### ISSUE TITLE
Enhance monthly quota fixtures

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/rosie#107]
In order to add the code structure add by #78 I merged the PR, but removed the lines that test its new feature, because I didn't know how to figure out them quickly, so I preferred to merge the code and update the fixture later.

The lines removed are here: https://github.com/datasciencebr/rosie/pull/78/commits/821ca679120b35b5ec242ba0bc5a0454ebd2289e

**Comment by cuducos** [comment]
Fixed by #109
