### ISSUE TITLE
Change irregularities.xz to be aligned with Jarbas

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/rosie#11]
Following what I agreed with @Irio and [implemented in Jarbas](https://github.com/datasciencebr/jarbas/commit/548e5ae4776659a9cf6f177d669c467525223ce2) we need a slightly different `YYYY-MM-DD-irregularities.xz`.

It must have:

* 2 columns with integers for `applicant_id`, `year` and `document_id`
* 1 column with a boolean for each hypothesis
* optionally one column with  `probability` float  (`0 <= probability <= 1`)

Example:

```csv
applicant_id,year,document_id,over_monthly_quota,travel_speed,invalid_cpnj_cpf,probability
1161,2013,567890,True,False,True,0.38
```

Or (as `probability` is optional):

```csv
applicant_id,year,document_id,over_monthly_quota,travel_speed,invalid_cpnj_cpf
1161,2013,567890,True,False,True
```

**Comment by Irio** [comment]
@cuducos Is this everything for now? https://github.com/datasciencebr/rosie/compare/irio-irregularity-files-format?expand=1

**Comment by cuducos** [comment]
Yep. I mean… _yep_ for the question. The link takes me to a page to open a PR. Not sure if that's what you mean.
