### ISSUE TITLE
Include twitter badge to Rosie

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/rosie#110]
There is a way to add a twitter badge on `README.md`.

It must look as something like this: `[![Follow](https://img.shields.io/twitter/follow/RosieDaSerenata.svg?style=social&label=Follow)](https://twitter.com/RosieDaSerenata)`

And Rosie's account: https://twitter.com/RosieDaSerenata

**Comment by desiby** [comment]
Hi! can I claim the issue?

**Comment by anaschwendler** [comment]
Sure @desiby! Please go on!

**Comment by anaschwendler** [comment]
Closed by #111
