### ISSUE TITLE
Update chronological sub-quota limits 

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/rosie#113]
Followin #3 we need to update the sub-quota limit classifier to adapt to values that have changed overtime (in pt-BR):

<img width="651" alt="screen shot 2017-12-05 at 09 06 01" src="https://user-images.githubusercontent.com/4732915/33604001-9d3d5f44-d99b-11e7-93ac-d0a98a0f6304.png">

**Comment by giovanisleite** [comment]
I can help with this one 😃
