### ISSUE TITLE
Anyone from law school can help us get historical sub-quota budget?

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/rosie#3]
When it concerns the hypothesis of a congressperson extrapolating the budget (limit) for each sub-quota forwssen by [CEAP](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#more-about-the-quota-for-exercising-parliamentary-activity-ceap) we were able to find the current limits, but some extra research is needed to find out the historical values — i.e. the values before the last proceedings.

We have data since 2011, but we only have the budget/limits for:

* _Automotive vehicle renting or watercraft charter_ from **01/04/2015**
* _Taxi, toll and parking_ from **01/04/2015**
* _Fuels and lubricants_ from **01/10/2015**
* _Security service provided by specialized company_ from **01/04/2015**
* _'Participation in course, talk or similar event_ from **01/11/2015**

If we have data about the budget/limits for the sub-cotas since 2011 [our robot](https://github.com/datasciencebr/rosie/blob/master/src/monthly_subquota_limit_classifier.py) could be even more precise.

**Comment by pmargreff** [comment]
@cuducos I open an issue and point all documents I have found, the limit for _Taxi, toll and parking_ and _Automotive vehicle renting_  [was established in 10/2013](https://github.com/datasciencebr/serenata-de-amor/issues/135). 

Another important point, when I made the pull request for serenata de amor project I understood each subquota (_Automotive vehicle_ / _watercraft_) have 10 k like limit, if it's the same 10k for both, and dataset is right, I think it will blow 1M in irregular spending easily. If you have sure the value is for the two categories, let me know for update the pull request.

**Comment by raphamendonca** [comment]
@cuducos I'm not from law school, but I found this post of Lucio Big, https://luciobig.com.br/ato-da-mesa-432009-camara-federal/, but the links was broken.
So I searched and found that references:
ATO DA MESA Nº 112, DE 15/10/2013 - http://bit.ly/2omT29W
ATO DA MESA Nº 116, DE 31/10/2013 - http://bit.ly/2omZQVn

**Comment by cuducos** [comment]
Thanks @raphamendonca — we had skim these texts before but we missed the opportunity to organize a kind of table with the compiled and relevant data when it comes to subquotas and limits. What I mean is something very straightforward such as a table with four columns: 

| Subquota | Limit | Start date | End date |
|-----------|------|-----------|----------|
| Fuel           | R$ 6k | 01/01/1970 | 25/12/1988 |
| Fuel           | R$ 5k | 26/12/1989 | 15/03/1992 |
| Car rental | R$ 11.9l | … | … |
| … | … | … | …|

If you're happy to organize that, this would be an awesome contribution ; )

**Comment by raphamendonca** [comment]
@cuducos OK. 
I Will check as many information as I could find. :)

**Comment by cuducos** [comment]
Thanks to Bruno Schimitt Morassutti we have all data we need!

<img width="651" alt="screen shot 2017-12-05 at 09 06 01" src="https://user-images.githubusercontent.com/4732915/33604001-9d3d5f44-d99b-11e7-93ac-d0a98a0f6304.png">
