### ISSUE TITLE
Travis is passing builds when it shouldn't

### ISSUE THREAD

**Issue by caiopo** [datasciencebr/rosie#43]
Travis exits with code 0 even when the tests fail.

https://travis-ci.org/datasciencebr/rosie/jobs/228188652

![image](https://cloud.githubusercontent.com/assets/12374562/25678399/f608319c-301f-11e7-9ac3-124f38c9b57a.png)

**Comment by anaschwendler** [comment]
Hi @caiopo, thanks for noticing!

We are working on turning the project generic to new datasets, so part of it involve adapting the rest of the code to it.
I'll be fixing it soon, thanks for warning us :)

**Comment by cuducos** [comment]
I couldn't understand why `The command "coverage run rosie.py test" exited with 0` when there is an error. Any ideas? I wrote to Travis support asking for ideas. Gonna update this topic if I hear from them.

**Comment by cuducos** [comment]
People form Travis CI are awesome — @cotsog explained:

> I had a look at your build log and your code and I believe this behavior comes from your test() function in the rosie.py file. Indeed, it seems that it's "swallowing" the exit code of the `testRunner.run(tests)` statement. To confirm, I would suggest changing your code for the following:

And basically the _following_ is #48 ; )

Let's see is that fixes, otherwise we can now use this `wasSuccessful` statement and explicitly `sys.exit(1)`.

Many thanks, @cotsog
