### ISSUE TITLE
Toolbox imports are broken

### ISSUE THREAD

**Issue by fariaslcfs** [datasciencebr/rosie#55]
Not quite sure, but...

```python
from serenata_toolbox.chamber_of_deputies.chamber_of_deputies_dataset import ChamberOfDeputiesDataset
```

`ChamberOfDeputiesDataset` does not exist in serenata-toolbox master branch.

![capturar](https://user-images.githubusercontent.com/3525791/27144630-fc30fef0-5108-11e7-9461-ae2f94f45726.PNG)

![capturar2](https://user-images.githubusercontent.com/3525791/27144658-2379ecb0-5109-11e7-9bd0-389f0605c3b8.PNG)

**Comment by cuducos** [comment]
Can you confirm which version of `serenata_toolbox` you have in Rosie's environment?

Try:

```
$ pip list | grep serenata_toolbox
```

If it's an older version than [11.1.1](https://github.com/datasciencebr/serenata-toolbox/blob/master/setup.py#L36) (what is at the toolbox's `master` branch) try to update it:

```
$ pip install -r requirements.txt
```

Then tells us if it works ; )

**Comment by cuducos** [comment]
Actually we changed toolbox API quite recently. Gonna open a PR to make Rosie follows this change. Thanks, @fariaslcfs ; )

**Comment by fariaslcfs** [comment]
The title looked more like a whole explanation than a title. kkk
Thanks you all for this awesome project.
