### ISSUE TITLE
Update subquota limit classifier

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/rosie#62]
There's a [new limit for renting cars](http://www2.camara.leg.br/legin/int/atomes/2017/atodamesa-183-16-maio-2017-784814-publicacaooriginal-152684-cd-mesa.html).

**Comment by ruan-brandao** [comment]
I'll start working on this one.

**Comment by cuducos** [comment]
Just a quick update: #86 and #87 are basically replacing the old value by the new value. This is not the idea. This classifier take into account, among other things, the date and the value. So we need to add a case and not remove the old ones… ok?
