### ISSUE TITLE
Fix documentation on running Rosie with docker

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/rosie#65]
Right now the docker file is doing what it is supposed to do but the command on running Rosie isn't correct. A fix is required here ;)

cc @Irio

**Comment by cuducos** [comment]
>  the command on running Rosie isn't correct

Is there an error or warning message?

**Comment by ThaisFaria** [comment]
Is it related to the Dockerfile? We ran into something similar yesterday while setting up the environment.

Replace line 
RUN ./setup

With 
RUN python setup

If it isn't it, I'll open a new issue. cc @jtemporal

**Comment by cuducos** [comment]
Also [the `CMD` is just `python rosie.py run`](https://github.com/datasciencebr/rosie/blob/master/Dockerfile#L25) when Rosie now expects do be called with an app like `python rosie.py run chamber_of_deputies` or `python rosie.py run federal_senate`…

**Comment by vtrbtf** [comment]
I was about to create the issue, but I think its not needed right now. 
Anyway, I was trying to run rosie locally. 
As @cuducos  mentioned, docs reference is wrong, it's being worked out.

FYI: sample of the error
```
teganheinopaparico@tepapariquei ~/projects/rosie (master)$ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie                               
A module must be provided.
Usage:
  python rosie.py run chamber_of_deputies [<path to output directory>]
Testing:
  python rosie.py test
  python rosie.py test chamber_of_deputies
```

**Comment by giovanisleite** [comment]
> Also the CMD is just python rosie.py run when Rosie now expects do be called with an app like python rosie.py run chamber_of_deputies or python rosie.py run federal_senate…

This sould be on dockerfile? And If the :person_fencing:  want to setup but not run immediately?

**Comment by cuducos** [comment]
> And If the 🤺 want to setup but not run immediately?

I think this is a good point. Maybe the `run` part should not be part of the Docker stuff. Docker tools leave the container ready but actually don't need to run Rosie — this could be a explicit call later.
