### ISSUE TITLE
Packaging?

### ISSUE THREAD

**Issue by jonDel** [datasciencebr/rosie#7]
It is not worth turning it into a pip package?

**Comment by vmesel** [comment]
@Irio should opinate. But I think its not necessary right now!

**Comment by cuducos** [comment]
IMHO Rosie dos not make sense as a pacakge to install via pip. It depends
on some local settings (config.ini), some specific environment (Anaconda
Python) and it's not a kind of "generic" tool (on the contrary, it tends to
be very specific). I vote for a better documentation on how to set it up,
but not to upload it in PyPI. (Related to that: a Dockerfile would be
awesome.)

**Comment by cuducos** [comment]
Closed by inactivity
