### ISSUE TITLE
Steps for Analyzing Rosie Records

### ISSUE THREAD

**Issue by mikaelhadler** [datasciencebr/rosie#70]
Guys, is there an instruction manual for analyzing the cases reported by Rosie?

I am looking for information on how to contribute with manual analysis of the records already identified as suspicious, but I did not find any information available.

How can I contribute to simplify this process for more people?

**Comment by cuducos** [comment]
Hi @mikaelhadler,

First of all I'd say you have to understand the legal part of the quota. The full text is available [from the Chamber of Deputies website](http://www2.camara.leg.br/legin/int/atomes/2009/atodamesa-43-21-maio-2009-588364-norma-cd-mesa.html) but you can find a more friendly TLDR at the main repo in [Portuguese](https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/CEAP_pt_BR.md) and [English](https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/CEAP.md).

From that it is an exercise of collecting contextual information about the reimbursement to confirm or reject the suspicion. There some articles describing some techniques and ideas we used [here](https://medium.com/data-science-brigade/como-está-acontecendo-a-hackaton-de-denúncias-da-operação-serenata-de-amor-a8bd193e0c76) and [there](https://medium.com/data-science-brigade/como-cidadãos-empoderados-podem-conversar-com-deputados-a24ad4020f1b) but there's no proper guide — I think each case requires a different approach.

Was that helpful?

**Comment by mikaelhadler** [comment]
Yes, very useful.

What I understood, that through [CEAP](https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/CEAP_pt_BR.md) we can obtain as premises that justify the expenses that this parliamentar can contain.

Therefore, it is possible to say that it is analyzed as premises of [CEAP](https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/CEAP_pt_BR.md) and there is for payment to CEAP, can we consider something to be investigated?

I would like to better understand a condition of analysis of the premises leading to suspect an expense, if possible, further simplify as analysis instructions, making it easier for those who want to collaborate with Rosie.

Thanks for answering.

**Comment by cuducos** [comment]
> I would like to better understand a condition of analysis of the premises leading to suspect an expense, if possible, further simplify as analysis instructions, making it easier for those who want to collaborate with Rosie.

I guess we are meaning different things when we use the words _analyze_, _investigate_ — and that's not a problem to worry about, it's just language ; )

When I first read your question I thought that was what you meant: _Ok, Rosie generates a file with some reimbursement classified as suspicious. But how can I analyze and investigate these reimbursements to know if Rosie got it right or if that was a false-positive?_ That was the kind of question my previous answer targeted.

But the part of your reply highlighted here has lead me to consider another perspective for your doubt: you might actually want to understand the logic underneath the classifiers that Rosie uses to say if a given reimbursement is or is nor suspicious (and, surely why she believes it might be).

If that's the case, the short answer is: every classifier has a corresponding notebook (or set of notebooks) in the [main repo](https://github.com/datasciencebr/serenata-de-amor) that tells you the story behind each one of them. For exemple, this is [the meal price outlier classifier](https://github.com/datasciencebr/rosie/blob/master/rosie/chamber_of_deputies/classifiers/meal_price_outlier_classifier.py) and this is [the notebook where we tested the analysis](https://github.com/datasciencebr/serenata-de-amor/blob/master/research/develop/2016-12-01-irio-anomalies-in-meal-prices.ipynb) until the point in which we were comfortable in porting it as a classifier. Or yet those are [the classifier](https://github.com/datasciencebr/rosie/blob/master/rosie/chamber_of_deputies/classifiers/traveled_speeds_classifier.py) and [notebook](https://github.com/datasciencebr/serenata-de-amor/blob/master/research/develop/2016-11-24-irio-traveled-speeds-between-meals.ipynb) related to our travel speed hypothesis. The longer version of this answer is [this article](https://medium.com/data-science-brigade/how-does-one-contribute-to-serenata-de-amor-operation-36e3e7b38207) ; )

Does that make sense?

**Comment by mikaelhadler** [comment]
Yeaah! Thank you so much for this instructions.
