### ISSUE TITLE
New bug while renaming categories

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/rosie#72]
As reported by @cuducos on #71 there's a bug when renaming the categories. I ran the code on master to check, it is there too, and [here is the traceback when running on master](https://gist.github.com/jtemporal/e071f71ab6e282bcce369d366aa4e935)

**Comment by jtemporal** [comment]
After a debugging session here found what is generating the traceback. Here it goes:

The [documentation on the data provided by the chamber of deputies](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/explicacoes-sobre-o-formato-dos-arquivos-xml) shows that the field `document_type` (indTipoDocumento) is supposed to have one of 3 values: zeros, ones and twos.

Running Rosie today, I've got **6** different values on that field.
<img width="314" alt="screen shot 2017-08-08 at 3 07 16 pm" src="https://user-images.githubusercontent.com/6595551/29087139-4dc45b3c-7c4b-11e7-9e80-a905ed770c1f.png">

Rosie is only is prepared to handle the 3 initially documented thus generating the nasty error reported here.

cc: @cuducos @Irio @vilapedro

**Comment by cuducos** [comment]
I think this should be reported to the Chamber of Deputies as an inconsistency in their API when compared to their documentation or the other way around.

Meanwhile we could:

* either convert `3`, `4` and `5` to `None`
* or try to match a CNPJ of CPF to try to properly guess what's the type of these rows

**Comment by jtemporal** [comment]
I'm converting everything to `None` until we hear back from them ;)
