### ISSUE TITLE
Different parameter value for  FIT and PREDICT STD DEV

### ISSUE THREAD

**Issue by edulemasson** [datasciencebr/rosie#80]
In the class MealPriceOutlierClassifier the predict outlier classifier use 3 standard deviations from average but the model FIT method is using 4 times Sigma.

So the accuracy and precision

**Comment by edulemasson** [comment]
Sorry, misclick.

So the accuracy and Precision calculus are biased.

**Comment by Irio** [comment]
Hi @edulemasson,

Would you mind being more specific about what you see as something wrong, why and what change you're suggesting?

**Comment by cuducos** [comment]
Closed by inactivity.  Feel free to re-open addressing @irio's question, @edulemasson ; )
